// <auto-generated/>
using InventoryUI.Services;
using Microsoft.AspNetCore.Components;
using Shared.DTOs;

namespace InventoryUI.Pages
{
    public partial class AuditReportsList
    {
        [Inject]
        public IFloorService AuditService { get; set; } = default!;

        [Inject]
        public NavigationManager NavManager { get; set; } = default!;

        protected bool IsLoading { get; set; } = true;
        protected List<AuditSessionListDTO> Sessions { get; set; } = new();

        protected override async Task OnInitializedAsync()
        {
            await LoadSessions();
        }

        private async Task LoadSessions()
        {
            try
            {
                IsLoading = true;
                // دالة تجلب جميع الجلسات من الـ API
                Sessions = await AuditService.GetAllAuditSessionsAsync();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error loading sessions: {ex.Message}");
            }
            finally
            {
                IsLoading = false;
            }
        }

        protected void ViewReport(int sessionId)
        {
            // التوجيه إلى صفحة المطابقة التي صممناها سابقاً
            NavManager.NavigateTo($"/audit/report/{sessionId}");
        }

        protected void NavigateToNewAudit()
        {
            NavManager.NavigateTo("/audit/new"); // مسار صفحة بدء جرد جديد
        }
    }
}
