// <auto-generated/>
using InventoryUI.Services;
using Microsoft.AspNetCore.Components;
using Shared.DTOs;

namespace InventoryUI.Pages
{
    public partial class AuditReportsList
    {
        [Inject]
        public IFloorService AuditService { get; set; } = default!;

        [Inject]
        public NavigationManager NavManager { get; set; } = default!;

        protected bool IsLoading { get; set; } = true;
        protected List<AuditSessionListDTO> Sessions { get; set; } = new();
        private MetaData MetaData { get; set; } = new MetaData();
        private int CurrentPage = 1;
        private int PageSize = 10;

        protected override async Task OnInitializedAsync()
        {
            await LoadSessions();
        }

        private async Task LoadSessions()
        {
            try
            {
                IsLoading = true;
                // استدعاء الخدمة مع تمرير رقم الصفحة الحالية
                var pagedResult = await AuditService.GetAllAuditSessionsAsync(CurrentPage, PageSize);

                Sessions = pagedResult.Items;
                MetaData = pagedResult.MetaData;
                if (MetaData != null && MetaData.CurrentPage > 0)
                {
                    CurrentPage = MetaData.CurrentPage;
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error loading sessions: {ex.Message}");
            }
            finally
            {
                IsLoading = false;
            }
        }
        private async Task SelectedPage(int page)
        {
            if (page >= 1 && page <= MetaData.TotalPages && page != CurrentPage)
            {
                CurrentPage = page;
                await LoadSessions();
            }
        }

        protected void ViewReport(int sessionId)
        {
            // التوجيه إلى صفحة المطابقة التي صممناها سابقاً
            NavManager.NavigateTo($"/audit/report/{sessionId}");
        }

        protected void NavigateToNewAudit()
        {
            NavManager.NavigateTo("/audit"); // مسار صفحة بدء جرد جديد
        }
    }
}
