// <auto-generated/>
using InventoryUI.Services;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;
using Shared.DTOs;

namespace InventoryUI.Pages
{
    public partial class LiveAudit
    {
        [Inject]
        public IFloorService AuditService { get; set; } = default!;
        [Inject]
        public NavigationManager NavManager { get; set; } = default!;
        protected ElementReference BarcodeInputRef;

        protected int SessionId { get; set; } = 0;
        protected int RoomId { get; set; }
        protected string Title { get; set; } = string.Empty;
        protected string CurrentBarcode { get; set; } = string.Empty;
        protected bool IsLoading { get; set; } = false;

        protected ScanResultDTO? LastResult { get; set; }
        protected AuditSummaryDTO? Summary { get; set; }
        protected List<Shared.DTOs.GetRoom> AvailableRooms { get; set; } = new();
        protected override async Task OnInitializedAsync()
        {
            try
            {
                // جلب قائمة الغرف من الـ API (تحتوي على Id و Name)
                AvailableRooms = await AuditService.GetRoomsAsync();
            }
            catch (Exception ex)
            {
                // يمكنك هنا إضافة نظام تنبيه (Toast) لعرض خطأ في جلب الغرف
                Console.WriteLine($"Error fetching rooms: {ex.Message}");
            }
        }

        protected async Task StartSessionAsync()
        {
            if (RoomId <= 0 || string.IsNullOrWhiteSpace(Title)) return;

            IsLoading = true;
            try
            {
                var dto = new CreateAuditSessionDTO { RoomId = RoomId, Title = Title };
                SessionId = await AuditService.StartSessionAsync(dto);
                await RefreshSummaryAsync();
            }
            finally
            {
                IsLoading = false;
                StateHasChanged();
                await Task.Delay(500); // إعطاء وقت للـ DOM ليتم رسمه
                await BarcodeInputRef.FocusAsync();
            }
        }

        protected async Task HandleKeyUpAsync(KeyboardEventArgs e)
        {
            if (e.Key == "Enter" && !string.IsNullOrWhiteSpace(CurrentBarcode))
            {
                if (long.TryParse(CurrentBarcode, out long barcodeValue))
                {
                    await ProcessScanAsync(barcodeValue);
                }

                CurrentBarcode = string.Empty;
                await BarcodeInputRef.FocusAsync();
            }
        }

        private async Task ProcessScanAsync(long barcode)
        {
            IsLoading = true;
            try
            {
                var dto = new ScanBarcodeDTO { AuditSessionId = SessionId, BarCode = barcode };
                LastResult = await AuditService.ScanBarcodeAsync(dto);

                await RefreshSummaryAsync();
            }
            catch (Exception)
            {
                LastResult = new ScanResultDTO
                {
                    Success = false,
                    Message = "حدث خطأ أثناء الاتصال بالخادم، يرجى المحاولة مرة أخرى.",
                    Status = ScanStatus.Unexpected
                };
            }
            finally
            {
                IsLoading = false;
            }
        }

        private async Task RefreshSummaryAsync()
        {
            Summary = await AuditService.GetSessionSummaryAsync(SessionId);
        }

        protected async Task ReconcileAndCloseAsync()
        {
            IsLoading = true;
            try
            {
                await AuditService.ReconcileSessionAsync(SessionId);
                NavManager.NavigateTo($"/audit/report/{SessionId}");
                // إعادة التهيئة لبدء جرد غرفة جديدة
                SessionId = 0;
                LastResult = null;
            }
            finally
            {
                IsLoading = false;
            }
        }
    }
}
