// <auto-generated/>
using InventoryUI.Services;
using Microsoft.AspNetCore.Components;

namespace InventoryUI.Pages
{
    public partial class PostAsset
    {
        [Parameter]
        public int RoomId { get; set; }

        [Inject]
        public IFloorService AssetService { get; set; } = default!;

        protected Shared.DTOs.PostAsset AssetModel { get; set; } = new();
        protected bool IsSubmitting { get; set; } = false;
        protected string Message { get; set; } = string.Empty;
        protected bool IsSuccess { get; set; } = false;

        protected override void OnInitialized()
        {
            // تثبيت رقم الغرفة الممرر عبر الرابط تلقائياً داخل النموذج
            AssetModel.RoomId = RoomId;
        }

        protected async Task HandleSubmit()
        {
            IsSubmitting = true;
            Message = string.Empty;

            // التأكد من تثبيت الـ RoomId الصحيح
            AssetModel.RoomId = RoomId;

            // إرسال البيانات للـ API
            var result = await AssetService.AddAssetAsync(AssetModel);

            IsSuccess = result.Success;
            Message = result.Message;

            if (result.Success)
            {
                // تصفير النموذج مع الإبقاء على رقم الغرفة
                AssetModel = new Shared.DTOs.PostAsset { RoomId = RoomId };
            }
            else
            {
                IsSuccess = false;
                Message = "حدث خطأ أثناء الاتصال بالـ API وتنسيق البيانات.";
            }


            IsSubmitting = false;
        }
    }
}
