// <auto-generated/>
using InventoryUI.Services;
using Microsoft.AspNetCore.Components;
using Microsoft.JSInterop;
using Shared.DTOs;

namespace InventoryUI.Pages
{
    public partial class ReconciliationReport
    {
        [Inject]
        public IFloorService AuditService { get; set; } = default!;

        // لحقن خدمة JS فقط لتشغيل أمر الطباعة المدمج في المتصفح
        [Inject]
        public IJSRuntime JS { get; set; } = default!;

        // يتم تمرير المعرف من الرابط /audit/report/{SessionId}
        [Parameter]
        public int SessionId { get; set; }

        protected bool IsLoading { get; set; } = true;
        protected ReconciliationReportDTO? Report { get; set; }

        protected override async Task OnInitializedAsync()
        {
            try
            {
                IsLoading = true;
                // يجب أن تضيف هذه الدالة في IAuditService لتجلب التقرير النهائي
                Report = await AuditService.GetReconciliationReportAsync(SessionId);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error loading report: {ex.Message}");
                // يفضل هنا استخدام Notification Service لإعلام المستخدم بالخطأ
            }
            finally
            {
                IsLoading = false;
            }
        }

        // دالة لطباعة التقرير مباشرة
        protected async Task PrintReport()
        {
            await JS.InvokeVoidAsync("window.print");
        }
    }
}
