// <auto-generated/>
using InventoryUI.Services;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.JSInterop;
using Shared.DTOs;

namespace InventoryUI.Pages
{
    public partial class ReconciliationReport : ComponentBase
    {
        // ⚠️ تعديل هام: تأكد من استخدام الـ Service الخاصة بالجرد وليس IFloorService
        [Inject]
        public IFloorService AuditService { get; set; } = default!;

        [Inject]
        public IJSRuntime JS { get; set; } = default!;

        [Parameter]
        public int SessionId { get; set; }

        // --- المتغيرات الأساسية للتقرير ---
        protected bool IsLoading { get; set; } = true;
        protected ReconciliationReportDTO? Report { get; set; }

        // --- متغيرات إضافة باركود جديد ---
        protected long NewBarcode { get; set; }
        protected bool IsProcessingScan { get; set; } = false;
        protected string? ScanErrorMessage { get; set; }
        protected ElementReference BarcodeImporter;

        // --- متغيرات الإغلاق ---
        protected bool IsFinalizing { get; set; } = false;

        protected override async Task OnInitializedAsync()
        {
            await LoadReportData();
        }

        // هذا التابع يركز مؤشر الماوس تلقائياً في حقل الباركود ليكون جاهزاً للمسح
        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (!firstRender && Report != null && Report.ClosedAt == default(DateTime) && !IsProcessingScan && !IsLoading)
            {
                try
                {
                    await BarcodeImporter.FocusAsync();
                }
                catch
                {
                    // تجاهل الخطأ في حال لم يتم العثور على العنصر في الـ DOM
                }
            }
        }

        private async Task LoadReportData()
        {
            try
            {
                IsLoading = true;
                Report = await AuditService.GetReconciliationReportAsync(SessionId);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error loading report: {ex.Message}");
                // يفضل هنا استخدام Notification Service لإعلام المستخدم بالخطأ
            }
            finally
            {
                IsLoading = false;
            }
        }

        // --- دوال إضافة مسحة جديدة ---

        // لالتقاط ضغطة زر الـ Enter من قارئ الباركود
        protected async Task HandleBarcodeScan(KeyboardEventArgs e)
        {
            if (e.Key == "Enter")
            {
                await SubmitScanInternal();
            }
        }

        protected async Task SubmitScanInternal()
        {
            if (NewBarcode==0 || IsProcessingScan || Report == null || Report.ClosedAt != default(DateTime))
                return;

            ScanErrorMessage = null;
            IsProcessingScan = true;

            try
            {
                // إرسال الباركود الجديد للـ API واستلام الـ DTO الخاص بالعنصر المضاف فقط
                // تأكد من إضافة الدالة AddScanToSessionAsync في IAuditService
                var newItem = await AuditService.AddScanToSessionAsync(SessionId, NewBarcode);

                UpdateReportLocally(newItem);

                NewBarcode =0; // تصفير الحقل للمسحة التالية
            }
            catch (Exception ex)
            {
                ScanErrorMessage = ex.Message;
            }
            finally
            {
                IsProcessingScan = false;
            }
        }

        // تحديث الواجهة محلياً (Optimistic UI) لسرعة الأداء بدون إعادة تحميل كل التقرير
        private void UpdateReportLocally(ScannedItemDTO apiItem)
        {
            if (Report == null) return;
            var newItem = new ReconciliationItemDTO
            {
                // انقل الخصائص المتطابقة بحسب أسماء الخصائص لديك
                Barcode = apiItem.Barcode,
                AssetNumber = apiItem.AssetNumber,
                AssetName = apiItem.AssetName,
                Specifications = apiItem.Specifications,
                FloorName = apiItem.FloorName,
                RoomName = apiItem.RoomName,
                Status = apiItem.Status,
           
                IsJustAdded = true // لتمييزه باللون الأخضر
            };

            // 2. البحث عن العنصر إذا كان مفقوداً مسبقاً وحذفه
            var existingItem = Report.Items.FirstOrDefault(i =>
                i.Barcode == newItem.Barcode && i.Status == ScanStatus.Unexpected);

            if (existingItem != null)
            {
                Report.Items.Remove(existingItem);
                Report.TotalMissing--;
            }

            // 3. إضافته في أول القائمة
            Report.Items.Insert(0, newItem);

            // 4. تحديث الإحصائيات
            if (newItem.Status == ScanStatus.Matched)
                Report.TotalMatched++;
            else if (newItem.Status == ScanStatus.Misplaced || newItem.Status == ScanStatus.Unexpected)
                Report.TotalMisplaced++;

            StateHasChanged(); // تحديث الواجهة
        }

        // --- دوال إغلاق الجلسة والطباعة ---

        protected async Task FinalizeSession()
        {
            if (IsFinalizing || Report == null) return;
            IsFinalizing = true;

            try
            {
                // تأكد من إضافة الدالة FinalizeAuditSessionAsync في IAuditService
                await AuditService.FinalizeAuditSessionAsync(SessionId);
                Report.ClosedAt = DateTime.Now; // سيؤدي هذا لإخفاء حقل المسح وزر الاعتماد من الواجهة
                StateHasChanged();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error finalizing session: {ex.Message}");
                // إظهار رسالة خطأ للمستخدم
            }
            finally
            {
                IsFinalizing = false;
            }
        }

        protected async Task PrintReport()
        {
            await JS.InvokeVoidAsync("window.print");
        }
    }
}
