// <auto-generated/>
using InventoryUI.Services;
using Microsoft.AspNetCore.Components;
using Microsoft.JSInterop;
using Shared.DTOs;

namespace InventoryUI.Pages
{
    public partial class RoomAssets
    {
        [Parameter]
        public int RoomId { get; set; }

        [Inject]
        public IFloorService AssetService { get; set; } = default!;

        [Inject]
        public NavigationManager NavigationManager { get; set; } = default!;

        [Inject]
        public IJSRuntime JSRuntime { get; set; } = default!;

        protected List<Shared.DTOs.GetAsset> Assets { get; set; } = new();
        protected bool IsLoading { get; set; } = true;
        protected string SearchTerm { get; set; } = string.Empty;

        protected IEnumerable<Shared.DTOs.GetAsset> FilteredAssets =>
            Assets.Where(a =>
                string.IsNullOrWhiteSpace(SearchTerm) ||
                a.Name.Contains(SearchTerm, StringComparison.OrdinalIgnoreCase) ||
                a.BarCode.ToString().Contains(SearchTerm) ||
                (!string.IsNullOrEmpty(a.Description) && a.Description.Contains(SearchTerm, StringComparison.OrdinalIgnoreCase))
            );

        protected override async Task OnInitializedAsync()
        {
            await LoadAssets();
           

        }

        private async Task LoadAssets()
        {
            IsLoading = true;
            Assets = await AssetService.GetAssetsByRoomAsync(RoomId);
            IsLoading = false;
        }
        private async Task ConfirmDelete(int id, string assetName)
        {
            // إظهار رسالة تأكيد للمستخدم عبر JS Confirm
            bool confirmed = await JSRuntime.InvokeAsync<bool>("confirm", $"هل أنت تأكد من رغبتك في حذف الأصل '{assetName}'؟");

            if (confirmed)
            {
                var isSuccess = await AssetService.DeleteAssetAsync(id);
                if (isSuccess)
                {
                    // إزالة العنصر من القائمة المحلية فوراً لتحديث الواجهة دون الحاجة لإعادة تحميل الصفحة
                    Assets.RemoveAll(a => a.Id == id);

                    // يمكنك إضافة إشعار نجاح هنا (Toast / Alert)
                }
                else
                {
                    // إظهار رسالة خطأ في حال فشل الحذف
                    await JSRuntime.InvokeVoidAsync("alert", "حدث خطأ أثناء محاولة حذف الأصل.");
                }
            }
        }
        protected void EditAsset(int id)
        {
            NavigationManager.NavigateTo($"/edit-asset/{id}");
        }
        protected void GoBack()
        {
            NavigationManager.NavigateTo($"/floors");
        }

    }
}
