// <auto-generated/>
using InventoryUI.Services;
using Microsoft.AspNetCore.Components;
using Microsoft.JSInterop;
using Shared.DTOs;

namespace InventoryUI.Pages
{
    public partial class RoomAssets
    {
        [Parameter]
        public int RoomId { get; set; }

        [Inject]
        public IFloorService AssetService { get; set; } = default!;

        [Inject]
        public NavigationManager NavigationManager { get; set; } = default!;

        [Inject]
        public IJSRuntime JSRuntime { get; set; } = default!;

        protected List<Shared.DTOs.GetAsset> Assets { get; set; } = new();
        protected MetaData MetaData { get; set; } = new MetaData(); // إضافة بيانات الصفحات

        protected bool IsLoading { get; set; } = true;
        protected string SearchTerm { get; set; } = string.Empty;

        // متغيرات التنقل
        protected int CurrentPage { get; set; } = 1;
        protected int PageSize { get; set; } = 10;

        protected override async Task OnInitializedAsync()
        {
            await LoadAssets();
        }

        private async Task LoadAssets()
        {
            IsLoading = true;
            StateHasChanged();

            var pagedResult = await AssetService.GetAssetsByRoomAsync(RoomId, CurrentPage, PageSize, SearchTerm);

            Assets = pagedResult.Items;
            MetaData = pagedResult.MetaData;

            if (MetaData != null && MetaData.CurrentPage > 0)
            {
                CurrentPage = MetaData.CurrentPage;
            }

            IsLoading = false;
            StateHasChanged();
        }

        // دالة تنفذ عند الكتابة في شريط البحث أو مسحه
        protected async Task OnSearchChanged(ChangeEventArgs e)
        {
            SearchTerm = e.Value?.ToString() ?? string.Empty;
            CurrentPage = 1; // عند البحث الجديد نعود دائماً للصفحة الأولى
            await LoadAssets();
        }

        // دالة تغيير الصفحة
        protected async Task SelectedPage(int page)
        {
            if (MetaData != null && page >= 1 && page <= MetaData.TotalPages && page != CurrentPage)
            {
                CurrentPage = page;
                await LoadAssets();
            }
        }

        private async Task ConfirmDelete(int id, string assetName)
        {
            bool confirmed = await JSRuntime.InvokeAsync<bool>("confirm", $"هل أنت متأكد من رغبتك في حذف الأصل '{assetName}'؟");

            if (confirmed)
            {
                var isSuccess = await AssetService.DeleteAssetAsync(id);
                if (isSuccess)
                {
                    // إعادة تحميل البيانات من السيرفر لضمان تحديث الصفحات بشكل صحيح
                    await LoadAssets();
                }
                else
                {
                    await JSRuntime.InvokeVoidAsync("alert", "حدث خطأ أثناء محاولة حذف الأصل.");
                }
            }
        }

        protected void EditAsset(int id)
        {
            NavigationManager.NavigateTo($"/edit-asset/{id}");
        }

        protected void GoBack()
        {
            NavigationManager.NavigateTo($"/floors");
        }
    }
}
