// <auto-generated/>
using InventoryUI.Services;
using Microsoft.AspNetCore.Components;
using Shared.DTOs;

namespace InventoryUI.Pages
{
    public partial class RoomAssets
    {
        [Parameter]
        public int RoomId { get; set; }

        [Inject]
        public IFloorService AssetService { get; set; } = default!;

        [Inject]
        public NavigationManager NavigationManager { get; set; } = default!;

        protected List<Shared.DTOs.GetAsset> Assets { get; set; } = new();
        protected bool IsLoading { get; set; } = true;
        protected string SearchTerm { get; set; } = string.Empty;

        protected IEnumerable<Shared.DTOs.GetAsset> FilteredAssets =>
            Assets.Where(a =>
                string.IsNullOrWhiteSpace(SearchTerm) ||
                a.Name.Contains(SearchTerm, StringComparison.OrdinalIgnoreCase) ||
                a.BarCode.ToString().Contains(SearchTerm) ||
                (!string.IsNullOrEmpty(a.Description) && a.Description.Contains(SearchTerm, StringComparison.OrdinalIgnoreCase))
            );

        protected override async Task OnInitializedAsync()
        {
            await LoadAssets();
           

        }

        private async Task LoadAssets()
        {
            IsLoading = true;
            Assets = await AssetService.GetAssetsByRoomAsync(RoomId);
            IsLoading = false;
        }

        protected void GoBack()
        {
            NavigationManager.NavigateTo($"/floors");
        }
    }
}
