// <auto-generated/>
using InventoryUI.Services;
using Microsoft.AspNetCore.Components;

namespace InventoryUI.Pages
{
    public partial class UpdateAssets
    {
        [Parameter]
        public int AssetId { get; set; }

        [Inject]
        public IFloorService AssetService { get; set; } = default!;

        [Inject]
        public NavigationManager NavigationManager { get; set; } = default!;

        protected Shared.DTOs.PostAsset AssetModel { get; set; } = new();
        protected List<Shared.DTOs.GetFloor> Floors { get; set; } = new(); // قائمة الطوابق والغرف
        protected bool IsLoading { get; set; } = true;
        protected string ErrorMessage { get; set; } = string.Empty;
        protected int OriginalRoomId { get; set; }

        protected override async Task OnInitializedAsync()
        {
            IsLoading = true;

            // 1. جلب قائمة الطوابق والغرف للمنسدلة
            Floors = await AssetService.GetFloorsAsync(); // أو GetFloorsWithRoomsAsync حسب تسميتها لديك

            // 2. جلب بيانات الأصل الحالي
            var existingAsset = await AssetService.GetAssetByIdAsync(AssetId);

            if (existingAsset != null)
            {
                AssetModel = new Shared.DTOs.PostAsset
                {
                    Name = existingAsset.Name,
                    BarCode = existingAsset.BarCode,
                    Description = existingAsset.Description,
                    RoomId = existingAsset.RoomId // سيتم تحديده تلقائياً في الـ Dropdown
                };

                OriginalRoomId = existingAsset.RoomId;
            }
            else
            {
                ErrorMessage = "تعذر العثور على بيانات الأصل المطلوب.";
            }

            IsLoading = false;
        }

        protected async Task HandleValidSubmit()
        {
            if (AssetModel.RoomId <= 0)
            {
                ErrorMessage = "يرجى اختيار غرفة صالحة للأصل.";
                return;
            }

            IsLoading = true;

            var success = await AssetService.UpdateAssetAsync(AssetId, AssetModel);

            if (success)
            {
                // الانتقال إلى الغرفة الجديدة التي تم نقل الأصل إليها
                NavigationManager.NavigateTo($"/rooms/{AssetModel.RoomId}/assets");
            }
            else
            {
                ErrorMessage = "حدث خطأ أثناء حفظ التعديلات.";
                IsLoading = false;
            }
        }

        protected void GoBack()
        {
            if (OriginalRoomId > 0)
            {
                NavigationManager.NavigateTo($"/rooms/{OriginalRoomId}/assets");
            }
            else
            {
                NavigationManager.NavigateTo("/floors");
            }
        }
    }
}
    